# Introdução ao NumPy

O Python é conveniente, mas também pode ser lento. Porém, ele permite que você acesse bibliotecas que executam mais rapidamente códigos escritos em idiomas como o C. O NumPy é uma dessas bibliotecas: oferece alternativas rápidas para operações matemáticas no Python e foi criado para trabalhar de forma eficaz com grupos de números - como matrizes.

O NumPy é uma biblioteca extensa e, aqui, daremos apenas uma visão geral dele. Se você planeja fazer muitos cálculos no Python, aconselhamos que explore melhor a documentação para saber mais.

Importando o NumPy
Ao importar a biblioteca NumPy, o padrão mais frequentemente utilizado – inclusive aqui – é nomeá-la como np, conforme abaixo:

In [1]:
import numpy as np

Agora você pode usar a biblioteca pré-fixando o nome das funções e tipos com np., conforme você verá nos exemplos a seguir.

### Formatos e tipos de dados
A maneira mais comum de trabalhar com números no NumPy é pelos objetos ndarray. Eles são semelhantes às listas do Python, mas podem ter qualquer número de dimensões. Além disso, ndarray suporta operações matemáticas rápidas, que é exatamente o que queremos.

Como ele pode armazenar qualquer número de dimensões, você pode usar ndarrays para representar qualquer um dos tipos de dado que estudamos antes: escalares, vetores, matrizes ou tensores.

### Escalares
Escalares no NumPy são um pouco mais envolvidos que no Python. Em vez dos tipos básicos do Python, como int, float, etc., o NumPy permite que você especifique tipos assinados ou não, bem como diferentes tamanhos. Então, em vez do int do Python, você terá acesso a tipos como uint8, int8, uint16, int16, e daí em diante.

Esses tipos são importantes porque todos os objetos que você cria (vetores, matrizes, tensores), em algum momento, armazenam escalares. E quando você cria uma array no NumPy, pode especificar um tipo - porém, cada item da array deve ter o mesmo tipo. Nesse ponto, as arrays do NumPy são mais parecidas com as arrays C do que as listas do Python.

Se quiser criar uma array NumPy que possua um escalar, você faz isso mudando o valor para uma função array no NumPy, como segue:

In [2]:
s = np.array(5)

Você também pode fazer cálculos entre ndarrays escalares NumPy e escalares comuns do Python, como verá na aula sobre matemática com conhecimento de elementos.

Você pode ver o formato das suas arrays verificando o atributo shape. Então, se executar este código:

In [3]:
s.shape

()

você obterá o resultado, um par de parênteses vazio, (). Isso indica que ele tem zero dimensões.

Embora escalares estejam dentro das arrays, você ainda os usa como um escalar normal. Então, você pode digitar:

In [4]:
x = s + 3

e o x, agora, totalizará 8. Se você fosse conferir o tipo de x, descobriria que, provavelmente, é numpy.int64, porque ele trabalha com tipos NumPy, não Python.

A propósito, até mesmo tipos de escalar suportam a maioria das funções das arrays. Então, você pode inserir x.shape e obterá (), pois ele tem zero dimensões, mesmo não sendo um conjunto. Se você tentar fazer isso com um escalar normal de Python, obterá um erro.

### Vetores
Para criar um vetor, você terá que colocar uma lista do Python na função array, conforme abaixo:

In [5]:
v = np.array([1,2,3])

Se você verificar o atributo shape de um vetor, obterá um único número, representando o comprimento unidimensional do vetor. No exemplo acima, v.shape resultaria em (3,).

Agora que existe um número, você pode ver que o formato é uma tupla com o tamanho de cada uma das dimensões ndarrays. Para escalares, é somente uma tupla vazia, mas os vetores possuem uma dimensão, então, a tupla inclui um número e uma vírgula (o Python não entende (3) como uma tupla com um item, por isso exige uma vírgula. Você pode saber mais sobre tuplas aqui).

Você pode usar um elemento dentro do vetor usando índices, por exemplo:

In [6]:
x = v[1]

Agora, x é igual a 2.

O NumPy também suporta técnicas avançadas de indexação. Por exemplo, para acessar os itens do segundo elemento em diante, você usaria:

In [7]:
v[1:]

array([2, 3])

e obteria uma array de [2, 3]. A divisão do NumPy é bem poderosa, permitindo que você acesse qualquer combinação de itens em uma ndarray. Mas também pode ser um pouco complicado, então, é importante você ler sobre isso na documentação.

### Matrizes
Você pode criar matrizes usando a função array do NumPy, assim como fez com vetores. Porém, em vez de apenas entregar uma lista, você precisará fornecer uma lista de listas, onde cada lista representa uma linha. Então, para criar uma matriz 3x3 contendo os números 1 a 9, você pode fazer o seguinte:

In [8]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

Verificar o atributo shape resultaria na tupla (3, 3), para indicar que ele tem duas dimensões, cada uma delas com o comprimento 3.

Você pode acessar elementos de matrizes, assim como nos vetores, mas usando valores de índice adicionais. Então, para obter o número 6 na matriz acima, você teria que acessar m[1][2].

### Tensores
Os tensores são iguais aos vetores e matrizes, mas podem ter mais dimensões. Por exemplo, para criar um tensor de 3x3x2x1, você poderia fazer o seguinte:

In [10]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

t.shape

(3, 3, 2, 1)

Você pode acessar itens, assim como nas matrizes, mas com mais índices. Então, t[2][1][1][0] resultará em 16.

# Operações com conhecimento de elementos

### O estilo Python
Suponhamos que você tenha uma lista de números e queira adicionar 5 a cada item da lista. Sem o NumPy, você pode fazer algo como:

In [11]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

# agora, os valores contêm [6,7,8,9,10]

Isso faz sentido, mas envolve muito código a ser escrito e roda devagar, pois trata-se de Python puro.

Observação: caso você não esteja acostumado a usar operadores como +=, isso apenas significa "adicionar esses dois itens e armazenar o resultado no item da esquerda". É uma forma mais sucinta de escrever values[i] = values[i] + 5. O código que você vê nesses exemplos utiliza esses operadores sempre que possível.

### O estilo NumPy
No NumPy, poderíamos fazer o seguinte:

In [12]:
values = [1,2,3,4,5]
values = np.array(values) + 5

# agora, os valores são uma ndarray que contém [6,7,8,9,10]

Criar uma array pode parecer estranho, mas, normalmente, você armazenaria os dados em ndarrays de qualquer forma. Então, se você já tivesse uma ndarray chamada values, poderia ter feito apenas:

In [13]:
values += 5

Devemos destacar que o NumPy, na verdade, possui funções para coisas como adição, multiplicação, etc. Mas ele também suporta o uso de operações matemáticas padrão. Então, as duas linhas a seguir são equivalentes:

```
x = np.multiply(some_array, 5)
x = some_array * 5
```

Geralmente, usamos os operadores em vez das funções, pois eles são mais práticos para digitar e mais fáceis de ler. Mas, na verdade, isso depende de sua preferência pessoal.

Outro exemplo de operações com escalares e ndarrays. Digamos que você tenha uma matriz m e queira reutilizá-la, mas antes precisa ver todos os valores como zero. É simples, basta multiplicar por zero e colocar o resultado de volta na matriz, conforme segue:

```
m *= 0

# agora, todos os elementos em m são zero, independentemente de quantas dimensões eles têm operações em matrizes com conhecimento de elementos
```

As mesmas funções e operadores que trabalham com escalares e matrizes também trabalham com dimensões. Você só precisa se certificar de que os itens em que executa a operação possuem formatos compatíveis.

Digamos que você queira obter valores quadrados de uma matriz. Seria apenas x = m * m (ou, se quiser colocar o valor novamente como m, seria m *= m).

Isso funciona porque trata-se de uma multiplicação com conhecimento de elementos entre duas matrizes de formato idêntico (nesse caso, elas têm o mesmo formato porque são, na verdade, o mesmo objeto).

Segue um exemplo do vídeo:

In [15]:
a = np.array([[1,3],[5,7]])
a
# exibe o seguinte resultado:
# array([[1, 3],
#        [5, 7]])

b = np.array([[2,4],[6,8]])
b
# exibe o seguinte resultado:
# array([[2, 4],
#        [6, 8]])

a + b
# exibe o seguinte resultado:
#      array([[ 3,  7],
#             [11, 15]])

array([[ 3,  7],
       [11, 15]])

E, caso tente trabalhar com formatos incompatíveis, como nos outros exemplos do vídeo, você obterá um erro:

In [16]:
a = np.array([[1,3],[5,7]])
a
# exibe o seguinte resultado:
# array([[1, 3],
#        [5, 7]])
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# exibe o seguinte resultado:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a.shape
# exibe o seguinte resultado:
#  (2, 2)

c.shape
# exibe o seguinte resultado:
#  (3, 3)

a + b
# exibe o seguinte erro:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3)

array([[ 3,  7],
       [11, 15]])

Você aprenderá mais sobre o que "could not be broadcast together" significa em uma próxima aula, mas, por enquanto, basta observar que os dois formatos são diferentes e, portanto, não podemos executar uma operação com conhecimento de elemento.

### Multiplicação de Matrizes no NumPy
Você ouviu falar muito sobre multiplicação de matrizes nos últimos vídeos – agora, você verá como fazer isso com o NumPy. Porém, é importante saber que o NumPy suporta diversos tipos de multiplicação de matrizes.

### Multiplicação elemento a elemento
Você já viu algumas multiplicações de elemento a elemento. Isso é obtido com a função multiply ou o operador *. Apenas para relembrar, ela seria assim:

In [17]:
m = np.array([[1,2,3],[4,5,6]])
m
# exibe o seguinte resultado:
# array([[1, 2, 3],
#        [4, 5, 6]])

n = m * 0.25
n
# exibe o seguinte resultado:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

m * n
# exibe o seguinte resultado:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

np.multiply(m, n)   # equivalent to m * n
# exibe o seguinte resultado:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

### Produto da matriz
Para encontrar o produto da matriz, você usa a função matmul no NumPy.

Se os formatos forem compatíveis, então, será simples assim:

In [18]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# exibe o seguinte resultado:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a.shape
# exibe o seguinte resultado:
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
# exibe o seguinte resultado:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b.shape
# exibe o seguinte resultado:
# (4, 3)

c = np.matmul(a, b)
c
# exibe o seguinte resultado:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
c.shape
# exibe o seguinte resultado:
# (2, 3)

(2, 3)

In [19]:
# Se suas matrizes tiverem formatos incompatíveis, você obterá um erro, como o seguinte:
np.matmul(b, a)
# exibe o seguinte erro:
# ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

### Função dot no NumPy
Algumas vezes, você verá a função [dot] do NumPy (https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) em locais onde esperaria ver uma matmul. O que acontece é que o resultado de dot e matmul é o mesmo se as matrizes forem bidimensionais.

Então, estes resultados são equivalentes:

In [20]:
a = np.array([[1,2],[3,4]])
a
# exibe o seguinte resultado:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# exibe o seguinte resultado:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # você pode usar `dot` diretamente na `ndarray`
# exibe o seguinte resultado:
# array([[ 7, 10],
#        [15, 22]])

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

array([[ 7, 10],
       [15, 22]])

Embora essas funções exibam o mesmo resultados em dados bidimensionais, você deve estar atento a qual escolher quando estiver trabalhando com outros formatos de dado. Você pode ler mais sobre as diferenças e encontrar links para outras funções do NumPy na documentação do matmul e do dot.

### Transposição
É muito fácil fazer a transposição de uma matriz no NumPy. Basta acessar o atributo T. Há também uma função transpose(), que gera o mesmo resultado, mas você raramente a verá sendo usada, já que é muito mais fácil digitar T. :)

Por exemplo: