# Operações com conhecimento de elementos

### O estilo Python

Suponhamos que você tenha uma lista de números e queira adicionar 5 a cada item da lista. Sem o NumPy, você pode fazer algo como:

In [20]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

# agora, os valores contêm [6,7,8,9,10]
values

[6, 7, 8, 9, 10]

Isso faz sentido, mas envolve muito código a ser escrito e roda devagar, pois trata-se de Python puro.

### O estilo NumPy

No NumPy, poderíamos fazer o seguinte:

In [21]:
import numpy as np

values = [1,2,3,4,5]
values = np.array(values) + 5

# agora, os valores são uma ndarray que contém [6,7,8,9,10]
values

array([ 6,  7,  8,  9, 10])

Geralmente, usamos os operadores em vez das funções, pois eles são mais práticos para digitar e mais fáceis de ler. Mas, na verdade, isso depende de sua preferência pessoal.

Outro exemplo de operações com escalares e ndarrays. Digamos que você tenha uma matriz m e queira reutilizá-la, mas antes precisa ver todos os valores como zero. É simples, basta multiplicar por zero e colocar o resultado de volta na matriz, conforme segue:

```
# agora, todos os elementos em m são zero, independentemente de quantas dimensões eles têm
m *= 0
```

### Operações em matrizes com conhecimento de elementos

As mesmas funções e operadores que trabalham com escalares e matrizes também trabalham com dimensões. Você só precisa se certificar de que os itens em que executa a operação possuem formatos compatíveis.

Digamos que você queira obter valores quadrados de uma matriz. Seria apenas x = m * m (ou, se quiser colocar o valor novamente como m, seria m *= m).

Isso funciona porque trata-se de uma multiplicação com conhecimento de elementos entre duas matrizes de formato idêntico (nesse caso, elas têm o mesmo formato porque são, na verdade, o mesmo objeto).

In [22]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [23]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [24]:
a + b

array([[ 3,  7],
       [11, 15]])

E, caso tente trabalhar com formatos incompatíveis, como nos outros exemplos do vídeo, você obterá um erro:

In [25]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [26]:
a.shape

(2, 2)

In [27]:
c.shape

(3, 3)

In [28]:
a + c
# exibe o seguinte erro:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 