# Multiplicação de Matrizes no NumPy
Você ouviu falar muito sobre multiplicação de matrizes nos últimos vídeos – agora, você verá como fazer isso com o NumPy. Porém, é importante saber que o NumPy suporta diversos tipos de multiplicação de matrizes.

## Multiplicação elemento a elemento
Você já viu algumas multiplicações de elemento a elemento. Isso é obtido com a função multiply ou o operador *. Apenas para relembrar, ela seria assim:

In [2]:
import numpy as np

m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [4]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [5]:
np.multiply(m, n)   # equivalent to m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

## Produto da matriz
Para encontrar o produto da matriz, você usa a função matmul no NumPy.

Se os formatos forem compatíveis, então, será simples assim:

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a.shape

(2, 4)

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
b.shape

(4, 3)

In [10]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [11]:
c.shape

(2, 3)

In [13]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

Se suas matrizes tiverem formatos incompatíveis, você obterá um erro, como o descrito acima.

## Função dot no NumPy
Algumas vezes, você verá a função [dot] do NumPy (https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) em locais onde esperaria ver uma matmul. O que acontece é que o resultado de dot e matmul é o mesmo se as matrizes forem bidimensionais.

Então, estes resultados são equivalentes:

In [14]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [16]:
a.dot(a)  # você pode usar `dot` diretamente na `ndarray`

array([[ 7, 10],
       [15, 22]])

In [17]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])