# Transposição

É muito fácil fazer a transposição de uma matriz no NumPy. Basta acessar o atributo T. Há também uma função transpose(), que gera o mesmo resultado, mas você raramente a verá sendo usada, já que é muito mais fácil digitar T. :)

Por exemplo:

In [2]:
import numpy as np

In [3]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

O NumPy faz isso sem realmente mover nenhum dado na memória - ele apenas muda a maneira com que indexa a matriz original - então, é bastante eficiente.

Portanto, isso também significa que você precisa ter atenção para a forma como modifica objetos. Por exemplo, com a mesma matriz m usada acima, veja o que acontece se modificarmos um valor em sua transposição:

In [5]:
m_t = m.T
m_t[1][1] = 200
m_t

array([[  1,   5,   9],
       [  2, 200,  10],
       [  3,   7,  11],
       [  4,   8,  12]])

In [6]:
m

array([[  1,   2,   3,   4],
       [  5, 200,   7,   8],
       [  9,  10,  11,  12]])

Observe como isso modifica a matriz original! Então, é melhor apenas considerar a transposição como uma visão diferente da sua matriz, em vez de uma matriz diferente.

## Um caso de uso real
Não quero entrar em detalhes demais sobre redes neurais, porque elas ainda não foram abordadas, mas existe um lugar onde você quase certamente acabará usando transposição ou, pelo menos, pensará nisso.

Digamos que você tenha as duas matrizes a seguir, chamadas inputs e weights,

In [7]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [8]:
inputs.shape

(1, 4)

In [9]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [10]:
weights.shape

(3, 4)

Estou falando para que elas servem porque você aprenderá sobre isso mais adiante, mas você acabará precisando encontrar o produto matriz dessas duas matrizes.

Se usá-las como estão agora, você obterá um erro:

In [11]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

A mensagem de erro está dizendo que os formatos não são compatíveis porque 4 não é igual a 3. Você pode ver os tamanhos alinhados uns ao lado do outros e lembrar, com base nos vídeos sobre multiplicação de matrizes, que o número de colunas na matriz esquerda deve ser igual ao número de linhas da matriz direita.

É, isso não funciona, mas observe que, usando a transposição das matrizes weights, será:

In [12]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

Isso também funciona se você usar a transposição de inputs e trocá-las de ordem

In [13]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

As duas respostas são transposições uma da outra, então, a multiplicação que você usa depende apenas do formato em que você quer o seu resultado.